name: A1
description: $description
version: '1.0'
main: org.jerae.a1.A1
api-version: '26.2'
load: POSTWORLD
authors: [Jerae]
commands:
  a1:
    description: Main A1 command
    usage: /a1 <version|reload>
  nickname:
    description: Set your nickname
    usage: /nickname [player] <displayName | -reset>
    aliases: [nick]
