name: A1
description: $description
version: '${version}'

main: org.jerae.a1.A1
api-version: '26.2'
load: POSTWORLD

authors: [Jerae]

commands:
  nickname:
    description: "Allows players to change their nickname"
    aliases:
      - nick
    usage: "/<command> [player] <displayName | -reset>"
  a1:
    description: "A1 plugin core commands"
    usage: "/<command> <version|reload>"
  afk:
    description: "Toggle AFK status"
    usage: "/<command>"
  rename:
    description: "Allows players to rename their held item"
    usage: "/<command> <displayName | -reset>"
  hat:
    description: "Wears an item on your head"
    usage: "/<command> [remove]"
