name: A1
description: $description
version: '${version}'

main: org.jerae.a1.A1
api-version: '26.2'
load: POSTWORLD

authors: [Jerae]
depend: [A2, A3]
softdepend: [A4]

commands:
  nick:
    description: "Allows players to change their nickname"
    aliases:
      - nickname
    usage: "/<command> [player] <displayName | -reset>"
  a1:
    description: "A1 plugin core commands"
    usage: "/<command> <version|reload>"
  afk:
    description: "Toggle AFK status"
    usage: "/<command>"
  rename:
    description: "Allows players to rename their held item"
    usage: "/<command> <displayName | -reset>"
  hat:
    description: "Wears an item from your selected item to your head"
    usage: "/<command> [remove]"
  a1dialog:
    description: "Internal command to open dialogs"
    usage: "/<command> <id>"
  tpa:
    description: "Request to teleport to another player"
    aliases:
      - tpask
    usage: "/<command> <player>"
  tpahere:
    description: "Request another player to teleport to you"
    aliases:
      - tpaskhere
    usage: "/<command> <player>"
  tpyes:
    description: "Accept a teleportation request"
    aliases:
      - tpaccept
    usage: "/<command>"
  tpno:
    description: "Decline a teleportation request"
    aliases:
      - tpdeny
    usage: "/<command>"
  tpaall:
    description: "Request all online players to teleport to you"
    aliases:
      - tpaaskall
    usage: "/<command>"
